Fix deep linking for app urls
expo/router pull request #371
Opened 2023-03-12 03:40 UTC by mauricedoepke

# Motivation
fixes #362 

# Execution
Compare uri scheme of the app with the link to handle links of the app itself. See https://github.com/expo/router/issues/362#issuecomment-1465077659 for in dephts explanation

# Test Plan
I adjusted the the existing snapshot tests to work with 2 slashes for custom urls instead of 3.

2023-03-12 14:02 UTC, RohovDmytro commented
Awesome!

Does it make sense to keep `extractExpoPathFromURL` naming for a more universal function?

2023-03-12 16:48 UTC, mauricedoepke commented
> Awesome!
> 
> Does it make sense to keep `extractExpoPathFromURL` naming for a more universal function?

That would indeed make sense. As this would increase the amount of changes I would first wait for feedback from EvanBacon on the current pr and then continue depending on that.

2023-03-15 17:43 UTC, EvanBacon commented on packages/expo-router/src/fork/extractPathFromURL.ts
> +  const isAppUrl = Constants.expoConfig?.scheme === res.scheme;
There can be multiple URI schemes in any app, meaning this is not a scaleable solution. Alternatively, could just check if the protocol is `['https', 'http']` to determine if the link is universal / web vs a deep link.

2023-03-15 17:43 UTC, EvanBacon requested changes
Thanks for taking this on, sorry for the inconvenience.

2023-03-16 17:14 UTC, mauricedoepke commented on packages/expo-router/src/fork/extractPathFromURL.ts
> +  const isAppUrl = Constants.expoConfig?.scheme === res.scheme;
I did the required change. I had to extend the exclusion to `['https', 'http', 'exp', 'exps']` though to handle expo urls that don't contain "--".

That was neccessary for e.g.: `exp://127.0.0.1:19000/`

2023-03-19 00:11 UTC, EvanBacon commented on packages/expo-router/src/fork/extractPathFromURL.ts
> +    res.scheme && !["https", "https", "exp", "exps"].includes(res.scheme);
This restricts other apps from using `exp` or `exps`, we can detect when running in Expo Go by using `Constants.executionEnvironment === ExecutionEnvironment.StoreClient`, other apps can't use `http` or `https` without being a valid browser (due to app store review restrictions).

2023-03-22 15:51 UTC, closed without merging

2023-03-22 15:54 UTC, mauricedoepke commented
@EvanBacon thanks for fixing this issue for us