refactor: do not force the use of expo-status-bar
expo/router pull request #773
Opened 2023-07-13 06:44 UTC by dylancom

# Motivation
Currently the use of the `<StatusBar />` component is forced, which leads to delayed status bar transitions upon closing a native modal.

Fixes: #772

2023-07-13 20:14 UTC, EvanBacon requested changes
This is a breaking change. For now, just move the StatusBar before the children line to allow overriding.

2023-07-14 06:37 UTC, dylancom commented
@EvanBacon that will result in the same error?

2023-07-14 11:44 UTC, dylancom commented
I updated the PR to a non breaking change. In case UIViewControllerBasedStatusBarAppearance was set in app.json, then <StatusBar /> won't be rendered. (any StatusBar that will be rendered will lead to a crash in that case).

2023-07-21 19:52 UTC, merged

2023-08-16 12:58 UTC, Malik-Usman17 commented
hello there i'm still facing the status bar same issue.

My **REACT NATIVE** version is **0.72.3**

2023-09-20 08:33 UTC, mozzius commented
This is working in production but dev client builds still have this issue